Enable Mojang offical auth forwarding. (#4)
bs-community/yggdrasil-api pull request #6
Opened 2018-07-31 14:17 UTC by cqjjjzr

添加了一个配置项。皮肤问题暂时忽略

Signed-off-by: Charlie Jiang <cqjjjzr@126.com>

2018-07-31 14:21 UTC, prinsss commented
请不要把 `vendor` 里的内容纳入版本管理，bs-community/blessing-skin-plugins 有 CI 自动构建的。

2018-07-31 14:26 UTC, printempw commented
另外，`join` 请求其实是可以不用转发的。

如果玩家是纯原版客户端，那么让他直接把 `join` 请求发到 Mojang 那边去，我们只需要转发 `hasJoined` 请求就可以了。

2018-07-31 14:33 UTC, cqjjjzr commented
Updated.

2018-07-31 14:36 UTC, cqjjjzr commented
测试本服务器优先模式，HMCL (正版登录)+1.7.10原版客户端+1.7.10原版服务器+authlib-injector 1.1.18测试通过。

2018-07-31 14:40 UTC, printempw commented
那个……请你使用 reset 后重新 commit 再 force push 好吗？你这样搞的话 `vendor` 里的内容就全部留在版本库里成垃圾了。

2018-07-31 14:44 UTC, cqjjjzr commented
Force pushed.

2018-07-31 15:09 UTC, prinsss requested changes
以及，请不要将 `composer.phar` 纳入版本管理。

2018-07-31 15:09 UTC, prinsss commented on src/Controllers/SessionController.php
> +function hasJoinedServerMojang(string $name, string $serverId, $ip) {
基本类型的 type hint 是从 PHP 7.0 开始支持的，本程序需要支持 PHP 5.5.9+。

2018-07-31 15:09 UTC, prinsss commented on .gitignore
> +vendor
请保留拖尾空行，并删去文件中间多余的空行

2018-07-31 15:09 UTC, printempw commented on composer.json
> +        "guzzlehttp/guzzle": "~6.0"
请先使用 `file_get_contents()` 替代，单独一个 GET 请求的转发不需要引入 Guzzle，而且新版 BS 将会添加此依赖。

2018-07-31 15:09 UTC, printempw commented on src/Controllers/SessionController.php
> -
请保留 `<?php` 与 `namespace` 之间的空行

2018-07-31 15:09 UTC, printempw commented on views/config.tpl
> +        ->option('mojang', '若 Mojang 官方验证服务器验证失败则使用本服务器')
我不明白这两个选项有什么实际的不同之处

2018-07-31 15:15 UTC, yushijinhun commented on views/config.tpl
> +        $form->select('ygg_mojang_forwarding', '服务器验证策略')
应当给出警告：正版用户将无法显示 Blessing skin 用户的皮肤。

2018-07-31 15:24 UTC, yushijinhun requested changes

2018-07-31 15:24 UTC, yushijinhun commented on src/Utils/helpers.php
> +            'ygg_mojang_forwarding' => 'blessing'
默认值应为 `blessing-only`。

2018-07-31 15:24 UTC, yushijinhun commented on src/Controllers/SessionController.php
> +function hasJoinedServerMojang(string $name, string $serverId, $ip) {
`ip` 参数不应当被发往 Mojang，原因如下：
1. BS 目前本身就不验证 ip
2. 如果中间有 Cloudflare 等 CDN，则无法获得真实 ip

2018-07-31 15:24 UTC, yushijinhun commented on views/config.tpl
> +        ->option('mojang', '若 Mojang 官方验证服务器验证失败则使用本服务器')
我认为只需要 `blessing`，不需要 `mojang`。除非你能给出一个 `mojang` 的适用场景。

2018-07-31 15:32 UTC, printempw commented on src/Controllers/SessionController.php
> +function hasJoinedServerMojang(string $name, string $serverId, $ip) {
不，这里的 `ip` 是由 Minecraft 服务端提供的（Query String 中），并不是 BS 获取的。既然服务端的 `hasJoined` 请求本来就带了 `ip` 参数，那我们也应该原样转发过去，和 BS 是否验证 IP 地址没关系吧？

2018-07-31 15:34 UTC, yushijinhun requested changes

2018-07-31 15:34 UTC, yushijinhun commented on src/Controllers/SessionController.php
> +            if ($response->getStatusCode() == 200) {
请更正缩进。

2018-07-31 15:34 UTC, yushijinhun commented on src/Controllers/SessionController.php
> +        if ($ip != null)
请加大括号。

2018-07-31 15:34 UTC, yushijinhun commented on src/Controllers/SessionController.php
> +        $client = new Client(['timeout' => 3.0]);
Mojang 的验证服务器延迟较大，3s 过短。请调到 5s 以上。

参考值：authlib 的超时时间为 15s。

2018-07-31 15:34 UTC, yushijinhun commented on views/config.tpl
> +        ->option('mojang', '若 Mojang 官方验证服务器验证失败则使用本服务器')
`mojang` 将会大大拖慢 Blessing skin 用户的验证时间。若非必须，请移除。

2018-07-31 16:28 UTC, cqjjjzr commented on views/config.tpl
> +        ->option('mojang', '若 Mojang 官方验证服务器验证失败则使用本服务器')
场景:大量正版用户，而盗版较少(例如一些小型基友服)，以及可能(但概率极小)产生的本服与官服token/uuid冲突

2018-07-31 16:33 UTC, yushijinhun commented on src/Controllers/SessionController.php
> +function hasJoinedServerMojang(string $name, string $serverId, $ip) {
貌似是我错了。可能需要实际测试一下。

2018-07-31 16:36 UTC, printempw commented on views/config.tpl
> +        ->option('mojang', '若 Mojang 官方验证服务器验证失败则使用本服务器')
那么让正版用户的请求先过一遍 BS 本身的逻辑也无伤大雅吧？反正正版用户也不会去请求 BS 本身的 `join` API，自然不会通过 `hasJoined` 的校验。至于 UUID 碰撞，如果真的要冲突的话，也和 Mojang 验证的先后顺序没有关系吧？

2018-08-01 00:30 UTC, cqjjjzr commented
All fixed.

2018-08-01 01:02 UTC, printempw commented
既然只有两种选择，不如将 `ygg_mojang_forwarding` 的值改为 true/false？

```
$form->checkbox('ygg_mojang_forwarding', '兼容正版验证')->label('用户进服验证失败时尝试使用 Mojang 官方验证服务器')->description('开启本选项后将允许正版用户直接进入服务器而无需通过 Blessing Skin 的验证。已知问题：正版用户将无法显示 BS 用户的皮肤，BS 用户也无法显示正版用户的皮肤（可以考虑使用皮肤 Mod 解决）。');
```

2018-08-01 01:17 UTC, cqjjjzr commented
Fixed.

2018-08-01 01:31 UTC, merged

2018-08-01 01:32 UTC, printempw commented
Thanks for your contribution. 👍

2018-08-01 02:09 UTC, yushijinhun reviewed
请对 [查询角色属性](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E6%9F%A5%E8%AF%A2%E8%A7%92%E8%89%B2%E5%B1%9E%E6%80%A7) 和 [按名称批量查询角色](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E6%8C%89%E5%90%8D%E7%A7%B0%E6%89%B9%E9%87%8F%E6%9F%A5%E8%AF%A2%E8%A7%92%E8%89%B2) 这两个 API 添加转发支持，否则会导致白名单无法添加正版用户等问题。

2018-08-01 08:02 UTC, cqjjjzr commented
存在一个问题，按名称批量查询角色非常容易导致问题，例如某用户同时在Blessing服务器与Mojang官方有注册，这时候就引出了问题了。我们不知道客户端进入服务器使用的是哪种方案，如果本服务器的结果优先则若正版登入就无法使用。

2018-08-01 08:05 UTC, printempw commented
所以你到底是个啥需求？是要让未经任何修改的官方客户端也能进入使用了本插件的服务器，还是让正版用户可以直接使用正版账号进服而无需注册皮肤站账号？

2018-08-01 08:08 UTC, cqjjjzr commented
两者皆是。当然皮肤的问题可能的确需要用CSL等解决方案，但至少没有经过任何修改的客户端能**进入**服务器，

2018-08-01 08:08 UTC, yushijinhun commented
我认为不应该合并有缺陷的功能进 yggdrasil-api。我建议将此 PR revert，然后在 yggdrasil-api 中添加接口用于拓展，再开一个新插件来实现你要求的功能。

2018-08-01 08:14 UTC, cqjjjzr commented
我目前并没有了解第二个API使用的场合。第一个API的转发已经实现。如果整个过程能避免实现第二个API的转发则可以降低一些问题。

2018-08-01 08:16 UTC, cqjjjzr commented
我认为如果给 yggdrasil-api 提供接口有过度设计的嫌疑。如果添加“插件的插件”实则是大幅提高了复杂度。

2018-08-01 08:20 UTC, cqjjjzr commented
另一个 solution 是直接 fork 出一个新的 plugin，称之为 `yggdrasil-api-forwarding` 等。

2018-08-01 08:24 UTC, printempw commented
后续讨论请前往 https://github.com/bs-community/yggdrasil-api/issues/4